.gitignore
docs/build.sh
docs/requirements.txt
docs/src/_static/css/titan.css
docs/src/conf.py
docs/src/index.rst

This adds the skeleton of docs infrastructure to the titan repo. This consists of a sphinx build using the readthedocs theme. Right now the content is empty, but I'd like to get this integrated so that we can work on the auto-generation of docs to titan-data.github.io.
Ran `build.sh` and viewed the content in `build/out`.

Beginning of docs infrastructure

---

docs/build.sh
docs/publish.sh
docs/src/conf.py
docs/src/index.rst

This adds a script to publish docs into a clone of the github.io repository. After this is merged, I'll work on the github actions infrastructure to automatically publish to the repository on commit to master and release tags.
Ran build & publish variations, verified site served up by jekyll.

initial docs publishing process

---

.github/workflows/docs-push.yml
docs/git-wrapper.sh
docs/publish.sh

This adds a new action that will take any pushes that change the `docs/*` directory, and publish this over to the titan-data.github.io under the `development` version. For this to work, the repo is configured with an SSH_PRIVATE_KEY that maps to an administrator on the titan-data.github.io repo, such that it can bypass review checks, etc. For the moment, I'm using my own SSH key, but we should configure a titan-automation machine user
Tested actions on my personal version of this repo.

action to update development documentation

---

docs/publish.sh

This is just a quick fix to include the version string in the commit message when we publish the docs. Should just make it a little easier to read/debug.

include version in docs push

---

docs/src/cli/cli.rst
docs/src/cli/cmd/checkout.rst
docs/src/cli/cmd/commit.rst
docs/src/cli/cmd/install.rst

This adds a few random commands so we can start to flesh them out and others can use them as a pattern.
Ran docs build and viewed result, checking for warnings in the process.

docs for a few CLI commands

---

.github/workflows/docs-push.yml

The github path matching uses go's Path.Match, which doesn't support recursive file handling. Instead, we have to add additional wildcarding for each level. This covers all current levels, but we'll have to be careful if we add more levels. Technically, it should be benign to run the action even if nothing has changed (because we track the hash), so we can also give up the path filtering if it becomes a problem.

trigger docs dev action for subdirectories

---

docs/build.sh

I noticed in the doc builds we were often updating the `.doctrees` directory, which seemed full of stuff not relavant to the actual output. Turns out this is true:
https://stackoverflow.com/questions/33904042/is-doctrees-folder-required-for-displaying-html-docs-with-sphinx
This uses the '-d' option
Ran build and verified that `.doctrees` no longer in output.

don't include .doctrees in output

---

docs/build.sh
docs/src/conf.py

We don't really need the "show page source" link on our docs, which is really used for cases where you're linking back to actual source code. This also minimizes the amount of stuff that has to be pushed to the titan-data.github.io repository.
Built locally and viewed result - no page source link. Verified that _sources was not in build/out, and grepped for _sources to make sure it wasn't still referenced somewhere.

don't include source links in docs

---

docs/src/lifecycle/diagnosis.rst
docs/src/lifecycle/supported.rst
docs/src/lifecycle/uninstall.rst
docs/src/lifecycle/upgrade.rst

This fleshes out the docs section around the software lifecycle. While there is some overlap with the commands themselves (like "titan install" vs. "Uninstalling Titan"), I think it's useful to keep a high level description here that can be more easily consumed and referenced from the CLI.
Built & viewed docs locally.

Software Lifecycle

---

.github/workflows/pull-request.yml
docs/src/lifecycle/diagnosis.rst

For the second time I pushed a change that broke the docs build. In addition to fixing the typo, I also updated the pull request action to build docs on PR. This should ensure that I never break anything again.
Opened a PR against my private repo and observed that the "Build Documentation" check ran successfully.

check docs on pull request

---

src/main/kotlin/io/titandata/titan/providers/local/RemoteList.kt

Fixes #55 
The two System.out.printf lines in the RemoteList function each had an extra string substitution that was preventing the remotes from being properly displayed.
Built jar, compiled binary, and tested on my local system.

removed two extraneous string substitutions

---

.github/workflows/docs-release.yml

Currently we trigger the docs release process for 'create', which includes branches. We've seen that when dependabot started creating branches, it broke this process since it didn't match the expected tag format. This will filter the process only for create operations in refs/tags. This is the same approach we use titan-server.

only run docs release when tags are created

---

src/main/kotlin/io/titandata/titan/Cli.kt
src/main/kotlin/io/titandata/titan/clients/Docker.kt
src/main/kotlin/io/titandata/titan/providers/Kubernetes.kt
src/main/kotlin/io/titandata/titan/providers/ProviderFactory.kt
src/main/kotlin/io/titandata/titan/providers/kubernetes/CheckInstall.kt
src/main/kotlin/io/titandata/titan/providers/kubernetes/Install.kt
src/main/kotlin/io/titandata/titan/providers/kubernetes/Uninstall.kt
src/test/kotlin/io/titandata/titan/clients/DockerTest.kt
src/test/kotlin/io/titandata/titan/providers/ProviderFactoryTest.kt

This adds a stub of a context for invoking titan-server in kubernetes context. This is activated by setting `TITAN_CONTEXT=kubernetes` in the environment. This runs an entirely parallel installation, with the identity "titan-k8s" instead of "titan", and running on port 5002 instead of 5002. This allows both contexts to co-exist during this alpha period (prior to having first-class context support). For now, we've just implemented the install/uninstall endpoints and list repositories.
I've held off writing extensive endtoend tests because there's still a lot of ambiguity around how this new context will evolve and how we'll automate access to shared k8s environments, etc.
Ran unit tests, as well as getting started end2end tests. Manual testing includes:
*Ability to run side-by-side*
```
$ …
```

initial kubernetes context stub

---

config/reflect-config.json
pom.xml
src/main/kotlin/io/titandata/titan/providers/Kubernetes.kt
src/main/kotlin/io/titandata/titan/providers/Local.kt
src/main/kotlin/io/titandata/titan/providers/generic/Status.kt

This moves the CLI to the 0.6.5 version of titan-server, and updates the volume status API as the only breaking change.
Maven tests, and end2end getting started tests.

update to 0.6.5

---

src/main/kotlin/io/titandata/titan/providers/local/Run.kt

The latest changes for `disablePortMapping` are a bit too aggressive in how they manage the port metadata. We want that flag to only control whether ports are mapped when we run the container, not whether they're persisted in the metadata. That way, a later clone can choose to forward those ports if it so desires.
Launched a container with `--disabplePortMapping`. Verified that ports were not mapped, but also that ports were present in the repo metadata.

add port metadata even if disablePortMapping set

---

config/reflect-config.json

A recent change introduced a mismerge that left `reflect-config` as invalid JSON due to a trailing comma. This fix eliminates the trailing comma.
Ran `build-osx`, which was previously failing.

fix reflect-config mismerge

---

pom.xml
src/main/kotlin/io/titandata/titan/providers/Kubernetes.kt
src/main/kotlin/io/titandata/titan/providers/Local.kt
src/main/kotlin/io/titandata/titan/providers/generic/Abort.kt
src/main/kotlin/io/titandata/titan/utils/OperationMonitor.kt

This updates the CLI to use titan server 0.6.6, which includes new operations APIs to better prepare for k8s support.
`mvn install`. Ran through getting started, verified progress messages displayed correctly. Logged into titan-server container and verified that volume sets were being reaped correctly while operation metadata remained in place. Ran through some tests with k8s and verified everything still worked correctly.

update to titan-server 0.6.6

---

scripts/windows/Dockerfile

Chocolatey package for graalvm updated to 19.3.0 and it looks like this broke the publishing workflow. Rolled back to 19.2.1

specify graal 19.2.1

---

.github/workflows/publish.yml

Windows builds are failing due to a missing C library. 
Temporarily disable windows build automation until Graal 19.3 can be tested and automated.

remove windows cicd until graal 19.3

---

src/main/kotlin/io/titandata/titan/clients/Docker.kt
src/main/kotlin/io/titandata/titan/providers/Kubernetes.kt
src/main/kotlin/io/titandata/titan/providers/Local.kt
src/main/kotlin/io/titandata/titan/providers/generic/Clone.kt
src/main/kotlin/io/titandata/titan/providers/generic/Pull.kt
src/main/kotlin/io/titandata/titan/providers/generic/Push.kt
src/main/kotlin/io/titandata/titan/providers/kubernetes/Install.kt
src/test/kotlin/io/titandata/titan/providers/generic/CloneTest.kt

This implements the remaining changes necessary to support k8s alpha using the master build of `titan-server`. This will be updated to use the official 0.7.0 `titan-server` build once it is available.
`mvn install` and getting started end2end tests. Manually ran through a number of k8s workflows, including cloning, pushing, and checking out repositories.

implement remaining k8s alpha functionality

---

pom.xml
src/main/kotlin/io/titandata/titan/providers/Kubernetes.kt
src/main/kotlin/io/titandata/titan/providers/Local.kt
src/main/kotlin/io/titandata/titan/providers/kubernetes/Uninstall.kt

This updates to the latest version of titan-server, in order to get k8s push & pull support. While I was testing, I also found an uninstall bug that was trying to remove the wrong volume when uninstalling under kubernetes context.
Ran `mvn install` and end2end tests. Did manual testing of push/pull and k8s workflow.

Update to titan-server 0.7.0

---

config/reflect-config.json
src/main/kotlin/io/titandata/titan/commands/List.kt
src/main/kotlin/io/titandata/titan/providers/Local.kt

We have built a custom version of 7.0.0 and placed it on the titan-data maven site until we can move to the next version, which will have a patch for the static V1PatchAdapter. Now that we're pulling this updated version, we can update the reflect config to properly support the patch operation needed for updating deployments (start, stop, checkout, etc).
I also noticed an "off by one" error between the various list commands, which I also fixed.
Verified that start/stop/checkout works now with native image.

update to custom 7.0.0 kubernetes java client

---

pom.xml

Jcenter now requires https as of January 2020. Project can't build as it is now

Changed jcenter dependencies in pom.xml to https from http
